### ISSUE TITLE
Поле ввода ответа закрыто кнопками, Nexus 5X

### ISSUE THREAD

**Issue by axl1232** [juick/Juick-Android#14]
![2016-07-22 11 25 43](https://cloud.githubusercontent.com/assets/4838041/17056707/924d7102-502e-11e6-9774-bac61583291f.png)
Не получается написать ответ.

**Comment by vitalyster** [comment]
Еще актуально?

**Comment by axl1232** [comment]
Нет, теперь все хорошо. Ну и я обновил ведро до 7.1.
![2017-01-27 08 26 42](https://cloud.githubusercontent.com/assets/4838041/22364629/9bb0a6d8-e494-11e6-89d5-8fe26e8bc574.png)

**Comment by vitalyster** [comment]
По-прежнему актуально, если сначала зайти в приватные сообщения
