### ISSUE TITLE
Pull-To-Refresh doesn't update messages

### ISSUE THREAD

**Issue by vitalyster** [juick/Juick-Android#16]
After pull to refresh I see new messages in log, but they do not update message lists - they still show old messages (need to restart app)

**Comment by alex0b** [comment]
Рестартовать необязательно, достаточно переключиться между вкладками.
К слову, через раз обновляется список комментов в треде (хотя нет данных, что это тот же самый баг, а не WS).

**Comment by alex0b** [comment]
[fixed](https://github.com/juick/Juick-Android/commit/ed37736eae56e8e47b98f16739160c1563a29843)
