### ISSUE TITLE
Xperia Z слишком крупные шрифты

### ISSUE THREAD

**Issue by UndeRus** [juick/Juick-Android#9]
У телефона разрешение 1920х1080 и даже самый мелкий шрифт, выставляемый жестом оказывается слишком крупным. Может надо учитывать физический размер дисплея?

**Comment by vitalyster** [comment]
актуально ли для текущей версии?

**Comment by UndeRus** [comment]
текущая версия вообще не логинится, не могу проверить

пт, 20 нояб. 2015 г. в 11:05, vitalyster <notifications@github.com>:

**Comment by vitalyster** [comment]
Именно та, что обновилась ночью - не логинится?

**Comment by UndeRus** [comment]
да, которая в плее лежит

пт, 20 нояб. 2015 г. в 11:47, vitalyster <notifications@github.com>:

**Comment by vitalyster** [comment]
android 6? https://juick.com/ в браузере горит красным?

**Comment by UndeRus** [comment]
Lollipop, нет, https красным не горит.

пт, 20 нояб. 2015 г. в 14:06, vitalyster <notifications@github.com>:

**Comment by vitalyster** [comment]
а гуглосервисы присутствуют?

**Comment by UndeRus** [comment]
да, присутствуют

пт, 20 нояб. 2015 г. в 15:40, vitalyster <notifications@github.com>:

**Comment by vitalyster** [comment]
Актуально ли сейчас на бета-версии?

**Comment by vitalyster** [comment]
Пинг?

**Comment by vitalyster** [comment]
Думаю, TextAppearance.AppCompat.Body1 - это правильный размер шрифта
